stages:
  heat_code:
    cmd: conda activate modelretrieval && poetry run python .\src\Experiments\exp_heat_signatures.py
    params:
    - code_extraction
    deps:
    - ./data/voxel_model
    - ./src/Experiments/exp_heat_signatures.py
    - ./src/signatures/heat_signature.py
    outs:
    - ./data/heat_signatures
  heat_code_comparison:
    cmd: conda activate modelretrieval && poetry run python ./src/Experiments/exp_code_distance.py
    params:
    - code_comparison
    deps:
    - ${code_comparison.code_path}
    outs:
    - ${code_comparison.save_path}
  statistic:
    cmd: conda activate modelretrieval && poetry run python ./src/Experiments/exp_similarity_statistcs.py
    params:
    - statistic
    deps:
    - ${statistic.similarity_path}
    - ./src/Experiments/exp_similarity_statistcs.py
    outs:
    - ${statistic.save_path}
    - ${statistic.truth_path}:
        persist: true
  hc_heat_code:
    cmd: conda activate modelretrieval && poetry run python ./src/Experiments/exp_cavity_code.py
    params:
    - cavity_code
    - code_extraction.steps
    - code_extraction.alpha
    deps:
    - ${cavity_code.hull_path}
    - ${cavity_code.cavity_path}
    - ./src/Experiments/exp_cavity_code.py
    - ./src/signatures/heat_signature.py
    outs:
    - ${cavity_code.save_path}
  hc_heat_code_comparison:
    cmd: conda activate modelretrieval && poetry run python ./src/Experiments/exp_cavity_code_similarity.py
    params:
    - cavity_comparison
    deps:
    - ${cavity_comparison.code_path}
    outs:
    - ${cavity_comparison.save_path}
  hc_heat_code_statistic:
    cmd: conda activate modelretrieval && poetry run python ./src/Experiments/exp_cavity_heat_statistics.py
    params:
    - hc_statistic
    deps:
    - ${hc_statistic.code_path}
    - ./src/Experiments/exp_cavity_heat_statistics.py
    outs:
    - ${hc_statistic.save_path}
  n2_statistic:
    cmd: conda activate modelretrieval && poetry run python ./src/Experiments/exp_n2_statistics.py
    params:
    - n2_statistic
    deps:
    - ${n2_statistic.code_path}
    - ./src/Experiments/exp_n2_statistics.py
    outs:
    - ${n2_statistic.save_path}
  n2_hull_code:
    cmd: conda activate modelretrieval && poetry run python ./src/Experiments/exp_n2_hull_code.py
    params:
    - n2_hull_code
    deps:
    - ${n2_hull_code.model_path}
    outs:
    - ${n2_hull_code.save_path}
  n2_hull_similarity:
    cmd: conda activate modelretrieval && poetry run python ./src/Experiments/exp_n2_hull_code_similarity.py
    params:
    - n2_hull_code_similarity
    deps:
    - ${n2_hull_code_similarity.code_path}
    outs:
    - ${n2_hull_code_similarity.save_path}
  n2_hull_statistic:
    cmd: conda activate modelretrieval && poetry run python ./src/Experiments/exp_n2_hull_code_statistic.py
    params:
    - n2_hull_statistic
    deps:
    - ${n2_hull_statistic.sim_path}
    outs:
    - ${n2_hull_statistic.save_path}


plots:
- dvclive/n2_hull_pr/plots/custom/Count FScore.json:
    x: count
    y: FScore
    x_label: Count
    y_label: FScore
- dvclive/n2_pr/plots/custom/Count FScore.json:
    x: count
    y: FScore
    x_label: Count
    y_label: FScore
- dvclive/pr/plots/custom/Count FScore.json:
    x: count
    y: FScore
    x_label: Count
    y_label: FScore
- dvclive/hc_pr/plots/custom/Count FScore.json:
    x: count
    y: FScore
    x_label: Count
    y_label: FScore
- dvclive/pr/plots/custom/PR Curve.json:
    template: linear
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/pr/plots/custom/Count pr curve.json:
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/pr/plots/custom/Thres FScore.json:
    x: thres
    y: FScore
    x_label: Threshold
    y_label: FScore
- dvclive/pr/plots/custom/Count FScore.json:
    x: count
    y: FScore
    x_label: Count
    y_label: FScore
- dvclive/hc_pr/plots/custom/PR Curve.json:
    template: linear
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/hc_pr/plots/custom/Count pr curve.json:
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/hc_pr/plots/custom/Thres FScore.json:
    x: thres
    y: FScore
    x_label: Threshold
    y_label: FScore
- dvclive/hc_pr/plots/custom/Count FScore.json:
    x: count
    y: FScore
    x_label: Count
    y_label: FScore
- dvclive/pr/plots/custom/PR Curve.json:
    template: linear
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/pr/plots/custom/Count pr curve.json:
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/pr/plots/custom/Thres FScore.json:
    x: thres
    y: FScore
    x_label: Threshold
    y_label: FScore
- dvclive/pr/plots/custom/Count FScore.json:
    x: count
    y: FScore
    x_label: Count
    y_label: FScore
- dvclive/hc_pr/plots/custom/PR Curve.json:
    template: linear
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/hc_pr/plots/custom/Count pr curve.json:
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/hc_pr/plots/custom/Thres FScore.json:
    x: thres
    y: FScore
    x_label: Threshold
    y_label: FScore
- dvclive/hc_pr/plots/custom/Count FScore.json:
    x: count
    y: FScore
    x_label: Count
    y_label: FScore
- dvclive/pr/plots/custom/PR Curve.json:
    template: linear
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/pr/plots/custom/Count pr curve.json:
    x: recall
    y: precision
    x_label: Recall
    y_label: Precision
- dvclive/pr/plots/custom/Thres FScore.json:
    x: thres
    y: FScore
    x_label: Threshold
    y_label: FScore
- dvclive/pr/plots/custom/Count FScore.json:
    x: count
    y: FScore
    x_label: Count
    y_label: FScore
metrics:
- dvclive/n2_hull_err/metrics.json
- dvclive/n2_err/metrics.json
- dvclive/err/metrics.json
- dvclive/hc_err/metrics.json
- dvclive/err/metrics.json
- dvclive/hc_err/metrics.json
- dvclive/err/metrics.json
- dvclive/hc_err/metrics.json
- dvclive/err/metrics.json
