code_extraction:
  model_path: ./data/voxel_model
  save_path: ./data/heat_signatures
  dim: 32
  steps: 32
  alpha: 0.04
code_comparison:
  code_path: ./data/heat_signatures/heat_codes.json
  save_path: ./data/heat_code_distance
statistic:
  similarity_path: ./data/heat_code_distance/
  truth_path: ./data/similarity_truth.json
  save_path: ./data/statistic
  volume_thres: 0.8
  ssa_thres: 0.8
cavity_code:
  hull_dim: 32
  cavity_dim: 8
  hull_path: ./data/fill_inside/
  cavity_path: ./data/labeled_cavities/
  save_path: ./data/cavity_code/
cavity_comparison:
  save_path: ./data/cavity_comparison
  code_path: ./data/cavity_code
hc_statistic:
  code_path: ./data/cavity_comparison/
  save_path: ./data/hc_statistic
  volume_thres: 0.8
  ssa_thres: 0.8
  truth_path: ./data/similarity_truth.json
n2_statistic:
  code_path: ./data/n2_comparison/
  save_path: ./data/n2_statistic
  volume_thres: 0.8
  ssa_thres: 0.8
  truth_path: ./data/similarity_truth.json
n2_hull_code:
  model_path: ./data/voxel_model
  save_path: ./data/n2_hull_code
  shape:
  - 64
  - 64
  - 64
  dim: 60
n2_hull_code_similarity:
  code_path: ./data/n2_hull_code/n2_hull_code.json
  save_path: ./data/n2_hull_code_similarity
n2_hull_statistic:
  sim_path: ./data/n2_hull_code_similarity
  save_path: ./data/n2_hull_statistic
  volume_thres: 0.8
  ssa_thres: 0.8
  truth_path: ./data/similarity_truth.json

